### ISSUE TITLE
GemBox.Document not working in Docker

### ISSUE THREAD

**Issue by sunny1028** [GemBoxLtd/GemBox.Document.Examples#1]
**I apologize for my poor English. I have deployed my .NET Core 7 program in Docker using the mcr.microsoft.com/dotnet/aspnet:7.0 image.**

**The following line of code is causing an error:**
`DocumentModel.Load(wordFileName).Save(outputPdfTemp);`

**The error message is as follows:**

Unable to load shared library 'libHarfBuzzSharp' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 

/app/runtimes/linux-x64/native/libHarfBuzzSharp.so: cannot open shared object file: No such file or directory

/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.10/libHarfBuzzSharp.so: cannot open shared object file: No such file or directory

/app/libHarfBuzzSharp.so: cannot open shared object file: No such file or directory

/app/runtimes/linux-x64/native/liblibHarfBuzzSharp.so: cannot open shared object file: No such file or directory

/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.10/liblibHarfBuzzSharp.so: cannot open shared object file: No such file or directory

/app/liblibHarfBuzzSharp.so: cannot open shared object file: No such file or directory

/app/runtimes/linux-x64/native/libHarfBuzzSharp: cannot open shared object file: No such file or directory

/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.10/libHarfBuzzSharp: cannot open shared object file: No such file or directory

/app/libHarfBuzzSharp: cannot open shared object file: No such file or directory

/app/runtimes/linux-x64/native/liblibHarfBuzzSharp: cannot open shared object file: No such file or directory

/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.10/liblibHarfBuzzSharp: cannot open shared object file: No such file or directory

/app/liblibHarfBuzzSharp: cannot open shared object file: No such file or directory

**Comment by mario-gembox** [comment]
Hi,

Please check the project file of our Docker example:
[GemBox.Document.Examples/C#/Platforms/Docker/DocumentDocker.csproj](https://github.com/GemBoxLtd/GemBox.Document.Examples/blob/de510c7e905aeff4407a78e3961487e66b24e9e7/C%23/Platforms/Docker/DocumentDocker.csproj)

I believe the issue you're experiencing occurs because the following package reference is missing in your project:
```xml
<PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="*" />
```

Also, please read our [Docker](https://www.gemboxsoftware.com/document/examples/create-word-pdf-on-docker-net-core/5902) example for more information about using GemBox.Document on Docker.

I hope this helps.

Regards,
Mario

**Comment by sunny1028** [comment]
Nice! It is working fine now. Thank you!
